### ISSUE TITLE
Building base containers fails

### ISSUE THREAD

**Issue by MakisH** [FoamScience/openfoam-apptainer-packaging#5]
@FoamScience thank you for presenting this at the [OpenFOAM RSE Special Interests Group](https://wiki.openfoam.com/Research_Software_Engineering_Special_Interest_Group)!

Following the instructions in the `README.md`, I get an error at the step where Ansible tries to build the base containers:

```
$ ansible-playbook build.yaml --extra-vars "original_dir=$PWD" --extra-vars "@config.yaml"

...

 _________________________________
< TASK [Build project containers] >
 ---------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

failed: [localhost] (item={'base_container': 'opencfd-openfoam', 'definition': 'projects/test.def', 'build_args': {'branch': 'master'}, 'name': 'test-master'}) => {"ansible_loop_var": "item", "changed": true, "cmd": "apptainer build --force      --warn-unused-build-args  --build-arg BRANCH=master    --build-arg CONTAINERS_DIR=/home/gc/Desktop/openfoam-apptainer-packaging/containers      --build-arg BASE_CONTAINER=opencfd-openfoam      --build-arg OS_VERSION=24.04      --build-arg MPI_VERSION=4.1.5      --build-arg FRAMEWORK_VERSION=2312      --build-arg FRAMEWORK_GIT_REF=default      /home/gc/Desktop/openfoam-apptainer-packaging/containers/projects/test-master.sif      /home/gc/Desktop/openfoam-apptainer-packaging/projects/test.def      > test-master.log 2>&1\n", "delta": "0:00:04.523143", "end": "2024-10-22 19:02:45.995097", "item": {"base_container": "opencfd-openfoam", "build_args": {"branch": "master"}, "definition": "projects/test.def", "name": "test-master"}, "msg": "non-zero return code", "rc": 255, "start": "2024-10-22 19:02:41.471954", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
 ____________
```

If I understand correctly, the CI currently [fails](https://github.com/FoamScience/openfoam-apptainer-packaging/actions/runs/11289275884/job/31766572497) at the same step (but probably for different reason, and gives more log files).

Should this be working?
How can I get more information about the exact issue? The only additional files I get are a [`test-master.log`](https://github.com/user-attachments/files/17479871/test-master.log) with the post scriplet failing at the step of testing the OpenMPI implementation, and two `.sif` image files.

I am running on Ubuntu 22.04 with freshly installed Apptainer 1.3.4 from their ppa and Ansible 2.17.5 from pip.

My main goal here is to learn, so I am very interested in any debugging clues.

**Comment by FoamScience** [comment]
Thanks!

YES, this would just work... the CI failure is unrelated, and not our responsibility for now.

Each `apptainer build` command that gets triggered will get you a log file; if there is no log file for any container, it means the workflow "downloaded" the base containers from the Github Container Registry instead of building them (I assume this will be faster). That's why you get only the log for the project container. You can disable this behavior by setting `pull.try_to_pull` to false, and **removing the container files**. If the base container files are found, they are not rebuilt.

The workflow will always rebuild the project containers though.

From your log, I see there is an issue with the linker not finding the mpi library so that is a bit strange. Maybe the containers I provide in the GHCR are faulty, so please try to rebuild everything locally by disabling the pull attempts.

Let me know if this solves the issue for you; so I can update the online containers, otherwise, `LD_LIBRARY_PATH`  probably doesn't have `/opt/ompi/lib` so the linker gets confused.

Currently I'm unable to reproduce this issue though...

You can see if MPI in the base container is fine with:
```bash
# <from this repo's root folder>
cd OMPIFoam
# <compile the example test binary>
apptainer run ../containers/basic/opencfd-openfoam.sif mpicc -o ./ompiTest testOMPI.cpp
# <run with 2 procs>
apptainer run ../containers/basic/opencfd-openfoam.sif mpirun -np 2 ./ompiTest
```
If this works,it means the base container is fine and the issue is in the definition file for the test project...

**Comment by FoamScience** [comment]
Also, CI will not pull from registries, so you could also get those containers [(job artifacts)](https://github.com/FoamScience/openfoam-apptainer-packaging/actions/runs/11289275884) and try them out.

**Comment by FoamScience** [comment]
Turns out it's just me forgetting to source OpenFOAM environment early enough xD
Thanks for the bug report though! This SOMEHOW was passing on my machine

**Comment by MakisH** [comment]
Thank you, this worked! :smile:
