### ISSUE TITLE
There is no runscript defined for this container (test-master)

### ISSUE THREAD

**Issue by MakisH** [FoamScience/openfoam-apptainer-packaging#6]
After building everything as suggested in the `README.md`:

```
$ ansible-playbook build.yaml --extra-vars "original_dir=$PWD" --extra-vars "@config.yaml"
...

 _________________________________
< TASK [Build project containers] >
 ---------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost] => (item={'base_container': 'opencfd-openfoam', 'definition': 'projects/test.def', 'build_args': {'branch': 'master'}, 'name': 'test-master'})
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=15   changed=7    unreachable=0    failed=0    skipped=9    rescued=0    ignored=0   
```

I tried to query into the project container, as suggested by the [OpenFOAM RSE talk slides](https://foamscience.github.io/openfoam-apptainer-containers-presentation/) (slides 42+44):

```
$ apptainer run containers/projects/test-master.sif info
There is no runscript defined for this container
```

@FoamScience Is this intended or does `projects/test.def` miss something?

**Comment by FoamScience** [comment]
Try `exec` instead of `run`
But we need a `%runscript` section in the definition file to source OpenFOAM automatically like I do [here](https://github.com/FoamScience/openfoam-apptainer-packaging/blob/6ebfcba0c1a804af52f6e51612f1f14f7578104e/basic/com-openfoam.def#L45)
This will get fixed shortly.
I genuinely thought If you omit the runscript section, the one from base containers would be active, but apparently not :)

**Comment by MakisH** [comment]
`exec` instead of `run` worked, thanks!
Let me know if you want contributions (I assume it is just easier for you to quickly do that).
